[files]
extend-exclude = [
	"ddnet-libs",
	"src/engine/external",
	"data/languages",
	"build/",
	"build-*/",
]

[default]
extend-ignore-re = [
	'InheretInfo',
	'Acale',
	'acutal',
	'aggressivly',
	'aling',
	'approriate',
	'asure',
	'Attachs',
	'avaliable',
	'BA',
	'buid',
	'Capabilites',
	'comando',
	'Compatibilty',
	'Confim',
	'Connnection',
	'datas',
	'Datas',
	'defered',
	'Destkop',
	'differenciate',
	'efficively',
	'entitys',
	'erro',
	'Erro',
	'Explicity',
	'explictly',
	'Exponention',
	'fo',
	'Fo',
	'FO',
	'Freeed',
	'FUL',
	'fullscren',
	'funtionality',
	'Garantees',
	'heigth',
	'Hight',
	'implentation',
	'infomation',
	'informations',
	'Inital',
	'iy',
	'layed',
	'Leafs',
	'leasure',
	'lod',
	'Lod',
	'LOD',
	'maches',
	'messege',
	'nteger',
	'occurence',
	'occurences',
	'omited',
	'OT',
	'PARM',
	'Pn',
	'PN',
	'posssible',
	'Predefineds',
	'PREDEFINEDS',
	'Preivew',
	'programatically',
	'recieve',
	'responible',
	'SEH',
	'Selecte',
	'seperate',
	'snapshoting',
	'thingie',
	'transfering',
	'tring',
	'unsed',
	'Verson',
	'VERTEXT',
	'Visbility',
	'whis',
	'Whis',
	'typ',
]
